extern const char PROGMEM http_http[8];
extern const char PROGMEM http_200[5];
extern const char PROGMEM http_301[5];
extern const char PROGMEM http_302[5];
extern const char PROGMEM http_get[5];
extern const char PROGMEM http_post[];
extern const char PROGMEM http_10[9];
extern const char PROGMEM http_11[9];
extern const char PROGMEM http_content_type[15];
extern const char PROGMEM http_texthtml[10];
extern const char PROGMEM http_location[11];
extern const char PROGMEM http_host[7];
extern const char PROGMEM http_crnl[3];
extern const char PROGMEM http_index_htm[11];
extern const char PROGMEM http_index_html[12];
extern const char PROGMEM http_404_html[10];
extern const char PROGMEM http_referer[9];
extern const char PROGMEM http_header_200[86];
extern const char PROGMEM http_header_400[];
extern const char PROGMEM http_header_404[93];
extern const char PROGMEM http_content_type_plain[29];
extern const char PROGMEM http_content_type_html[28];
extern const char PROGMEM http_content_type_css [27];
extern const char PROGMEM http_content_type_text[28];
extern const char PROGMEM http_content_type_png [28];
extern const char PROGMEM http_content_type_gif [28];
extern const char PROGMEM http_content_type_jpg [29];
extern const char PROGMEM http_content_type_binary[43];
extern const char PROGMEM http_html[6];
extern const char PROGMEM http_shtml[7];
extern const char PROGMEM http_htm[5];
extern const char PROGMEM http_css[5];
extern const char PROGMEM http_png[5];
extern const char PROGMEM http_gif[5];
extern const char PROGMEM http_jpg[5];
extern const char PROGMEM http_text[6];
extern const char PROGMEM http_txt[5];
