
$(curdir)-y += shell.c
$(curdir)-$(CONFIG_APPS_SHELL_BOOTLDR_UPG) += shell-bootldr_upg.c
$(curdir)-$(CONFIG_APPS_SHELL_DATE) += shell-date.c
$(curdir)-$(CONFIG_APPS_SHELL_FILE) += shell-file.c
$(curdir)-$(CONFIG_APPS_SHELL_FREE) += shell-free.c
$(curdir)-$(CONFIG_APPS_SHELL_INFO) += shell-info.c
$(curdir)-$(CONFIG_APPS_SHELL_LOG) += shell-log.c
$(curdir)-$(CONFIG_APPS_SHELL_NETSTAT) += shell-netstat.c
$(curdir)-$(CONFIG_APPS_SHELL_OWTEST) += shell-owtest.c
$(curdir)-$(CONFIG_APPS_SHELL_PS) += shell-ps.c
$(curdir)-$(CONFIG_APPS_SHELL_REBOOT) += shell-reboot.c
$(curdir)-$(CONFIG_APPS_SHELL_RLYTEST) += shell-rlytest.c
$(curdir)-$(CONFIG_APPS_SHELL_TFTP) += shell-tftp.c
$(curdir)-$(CONFIG_APPS_SHELL_UPTIME) += shell-uptime.c

$(eval $(call subdir,$(curdir)))
