
$(curdir)-y += shell.c
$(curdir)-$(CONFIG_APPS_SHELL_DATE) += shell-date.c
$(curdir)-$(CONFIG_APPS_SHELL_FILE) += shell-file.c
$(curdir)-$(CONFIG_APPS_SHELL_FREE) += shell-free.c
$(curdir)-$(CONFIG_APPS_SHELL_LOG) += shell-log.c
$(curdir)-$(CONFIG_APPS_SHELL_NETSTAT) += shell-netstat.c
$(curdir)-$(CONFIG_APPS_SHELL_OWTEST) += shell-owtest.c
$(curdir)-$(CONFIG_APPS_SHELL_PS) += shell-ps.c
$(curdir)-$(CONFIG_APPS_SHELL_REBOOT) += shell-reboot.c
$(curdir)-$(CONFIG_APPS_SHELL_TFTP) += shell-tftp.c

$(eval $(call subdir,$(curdir)))
