
$(curdir)-y += shell.c
$(curdir)-$(CONFIG_APPS_SHELL_BLINK) += shell-blink.c
$(curdir)-$(CONFIG_APPS_SHELL_COFFEE) += shell-coffee.c
$(curdir)-$(CONFIG_APPS_SHELL_FILE) += shell-file.c
$(curdir)-$(CONFIG_APPS_SHELL_FREE) += shell-free.c
$(curdir)-$(CONFIG_APPS_SHELL_NETSTAT) += shell-netstat.c
$(curdir)-$(CONFIG_APPS_SHELL_LOG) += shell-log.c
$(curdir)-$(CONFIG_APPS_SHELL_PING) += shell-ping.c
$(curdir)-$(CONFIG_APPS_SHELL_PS) += shell-ps.c
$(curdir)-$(CONFIG_APPS_SHELL_REBOOT) += shell-reboot.c
$(curdir)-$(CONFIG_APPS_SHELL_TEXT) += shell-text.c
$(curdir)-$(CONFIG_APPS_SHELL_VARS) += shell-vars.c

$(eval $(call subdir,$(curdir)))
