
$(curdir)-$(CONFIG_DRIVERS_DATAFLASH) += dataflash.c
$(curdir)-$(CONFIG_DRIVERS_DS1307) += ds1307.c
$(curdir)-$(CONFIG_DRIVERS_ENC28J60) += enc28j60.c
$(curdir)-$(CONFIG_DRIVERS_ENC424J600) += enc424j600.c
$(curdir)-$(CONFIG_DRIVERS_I2C) += i2c.c
$(curdir)-$(CONFIG_DRIVERS_SPI) += spi.c
$(curdir)-$(CONFIG_DRIVERS_UART) += uart.c

$(eval $(call subdir,$(curdir)))

