
$(curdir)-$(CONFIG_APPS_DHCP) += dhcp.c
$(curdir)-$(CONFIG_APPS_MONITOR) += monitor.c
$(curdir)-$(CONFIG_APPS_NETWORK) += network.c
$(curdir)-$(CONFIG_APPS_SERIAL) += serial.c
$(curdir)-$(CONFIG_APPS_SERIAL_SHELL) += serial-shell.c
$(curdir)-$(CONFIG_APPS_SHELL) += shell/
$(curdir)-$(CONFIG_APPS_TIMESYNC) += timesync.c
$(curdir)-$(CONFIG_APPS_WEBSERVER) += webserver/

$(eval $(call subdir,$(curdir)))

